class Strings {
  static const String home = 'Home';
  static const String about = 'About';
  static const String contact = 'Contact';
  static const String experience = 'Experience';
  static const String resume = 'Resume';
  static const String hi_text = "Hi! I'm,";
  static const String thanks = "Thanks For Looking!";
  static const String what_next = "Whats Next?";
  static const String my_projects = "My Projects";
  static const String Git_link = "https://github.com/Prathamesh72001";
  static const String Facebook_link = "https://www.facebook.com/profile.php?id=100010956733291&mibextid=ZbWKwL";
  static const String Linkedin_link = "https://www.linkedin.com/in/prathamesh-sawardekar-3671b9238";
  static const String Whatsapp_link = "https://wa.link/aiezfi";
  static const String Telegram_link = "https://telegram.me/prathamesh070401";
  static const String Instagram_link = "https://instagram.com/prathamesh_pratik_07?igshid=OGQ5ZDc2ODk2ZA==";
  static const String classmate = "Classmates";
  static const String classmate_desc = '''Classmates is an innovative educational platform designed to cater to students from tenth grade through graduation. This multifaceted project offers a comprehensive set of features to enhance the learning experience. Classmates is a versatile platform that empowers students with easy access to study resources, fosters communication with administrators, and promotes interactive learning through video chat capabilities."Classmates" is an innovative educational platform designed to cater to students from tenth grade through graduation. This multifaceted project offers a comprehensive set of features to enhance the learning experience. "Classmates" is a versatile platform that empowers students with easy access to study resources, fosters communication with administrators, and promotes interactive learning through video chat capabilities.''';
  static const String groccer_basket = "GrocersBasket";
  static const String groccer_basket_link = "https://github.com/Prathamesh72001/GrocersBasket";
  static const String groccer_basket_desc = '''GrocersBasket is a comprehensive eCommerce Android application designed to streamline the grocery shopping experience for users while offering a robust platform for sellers to market and manage their grocery products. It also provides essential administrative tools to oversee and support seller operations. GrocersBasket aims to revolutionize the grocery shopping experience by providing a convenient, efficient, and secure platform for users to purchase groceries while empowering sellers to expand their reach and streamline their operations. With its user-centric design and seller-focused services, GrocersBasket is set to become a cornerstone in the world of online grocery shopping.''';
  static const String adventure_time = "It's Adventure Time";
  static const String adventure_time_link = "https://github.com/Prathamesh72001/It-s-Adventure-Time";
  static const String adventure_time_desc = '''"It's Adventure Time" is a captivating 2D platformer game meticulously crafted using Unity, offering players a thrilling journey through a whimsical world. Join our intrepid hero on an epic quest as they traverse vibrant landscapes, confront cunning enemies, and solve intricate puzzles. The game provides a captivating blend of classic platformer gameplay with a fresh, modern twist, ensuring hours of engaging entertainment for players of all ages.''';
  static const String jyppzer = "JyppzerKids: Life Skills DIY";
  static const String jyppzer_link = "https://play.google.com/store/apps/details?id=com.jyppzer_android&pcampaignid=web_share";
  static const String jyppzer_desc = '''JyppzerKids is an enriching educational app designed to strengthen the parent-child bond while nurturing your child's holistic development from ages 0 to 12. With a treasure trove of 500+ age-appropriate activities and games, this platform offers a delightful way to lay a solid foundation for your child's future growth, including academic success.''';
  static const String canvia = "Canvia : Experience Art, Invoke";
  static const String canvia_link = "https://play.google.com/store/apps/details?id=com.canvia.palacio&pcampaignid=web_share";
  static const String canvia_desc = '''Canvia, is a smart art frame IOT project that enables “Art as an Experience.” Canvia, a smart art frame that uses the confluence of innovative technologies, device features and curated content to redefine “Art as an Experience”. Canvia gives customers the option to display a variety of artworks in a single frame, bringing flexibility to art buying.''';
  static const String iTap = "iTAP Entertainment & Gaming";
  static const String iTap_link = "https://stream.itap.online/,https://apps.apple.com/in/app/itap-entertainment-gaming/id6443938485,https://play.google.com/store/apps/details?id=com.app.itap&pcampaignid=web_share";
  static const String iTap_desc = '''iTap is a cutting-edge entertainment platform designed to offer a captivating and diverse range of content, akin to streaming giants like Netflix and Amazon Prime. As a dedicated Android developer for the Android app and a Flutter developer for the iOS and Web versions, I played a crucial role in bringing this multi-platform entertainment experience to life. iTap is not just an entertainment app; it's a platform that aims to redefine how people consume content. With a user-friendly interface, a vast content library, and cross-platform accessibility, iTap offers a top-tier entertainment experience for users across Android, iOS, and the web. As part of the development team, I contributed to creating an engaging, feature-rich, and highly accessible entertainment ecosystem.''';
  static const String get_in_touch = "Get In Touch";
  static const String name = "Prathamesh Sawardekar";
  static const String build_text = "Crafting Innovative Experiences as an Android & Flutter Developer. Exploring the Boundaries of Mobile Technology to Deliver Seamless and Intuitive Solutions.";
  static const String contact_text = "I'd love to hear from you,";
  static const String contact_sub_text = "Got a project you would like me to work on?\nOr how about just a friendly chat?";
  static const String about_text = "As an Android/Flutter developer, I have a strong foundation in mobile app development and a passion for creating innovative and user-friendly applications. With handful years of experience in the field, I have honed my skills in both Java and Kotlin for Android and Dart for Flutter. I excel in translating design concepts into functional and aesthetically pleasing apps, utilizing the latest technologies and best practices. My ability to collaborate effectively with cross-functional teams and adapt to rapidly changing industry trends has contributed to the successful delivery of projects. I am a problem solver at heart, dedicated to optimizing performance and ensuring a seamless user experience in every app I develop. My commitment to staying up-to-date with emerging technologies and my drive to continuously improve make me a valuable asset in the world of Android and Flutter development.";
}
